name: Update and Analyze Baserow Data
on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual triggering

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests matplotlib pandas statsmodels

      - name: Fetch Baserow data
        env:
          BASEROW_TOKEN: ${{ secrets.BASEROW_TOKEN }}
        run: |
          python fetch_baserow_data.py

      - name: Analyze data dynamically
        run: |
          python auto_analyze.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -A  # This ensures all new files are added
          git commit -m "Automated update: Latest Baserow data and analysis" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
